# Generated by Django 6.1 on 2026-08-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام شعبه')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='شماره تلفن')),
            ],
            options={
                'verbose_name': 'شعبه',
                'verbose_name_plural': 'شعب',
                'ordering': ['name'],
            },
        ),
    ]
