# Generated by Django 6.1 on 2026-08-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('depts', models.JSONField(blank=True, default=list, verbose_name='دپارتمان\u200cها')),
                ('reqtype', models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی')], default='حضوری', max_length=10, verbose_name='نوع همکاری درخواستی')),
                ('regtype', models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی')], default='حضوری', max_length=10, verbose_name='نحوه\u200cی ثبت درخواست')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(blank=True, max_length=13, verbose_name='کد پستی')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='نام کاربری پیشنهادی')),
                ('password_hash', models.CharField(blank=True, max_length=255, verbose_name='رمز عبور (هش\u200cشده)')),
                ('photo', models.FileField(blank=True, null=True, upload_to='teacher_applicants/photos/', verbose_name='عکس')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_applicants/resumes/', verbose_name='رزومه')),
                ('message', models.TextField(blank=True, verbose_name='توضیحات متقاضی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مدرس متقاضی',
                'verbose_name_plural': 'مدرسین متقاضی',
                'ordering': ['-created_at'],
            },
        ),
    ]
