# Generated by Django 6.1 on 2026-08-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_multi_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherapplicant',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='teacherapplicant',
            name='username',
        ),
    ]
