# Generated by Django 6.1 on 2026-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_teacherapplicant_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplicant',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد پستی'),
        ),
    ]
