# Generated by Django 6.1 on 2026-09-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_teacherapplicant_reqtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherapplicant',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='teacherapplicant',
            name='education_level',
            field=models.CharField(blank=True, choices=[('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکتری', 'دکتری')], max_length=20, verbose_name='میزان تحصیلات'),
        ),
        migrations.AddField(
            model_name='teacherapplicant',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
    ]
