# Generated by Django 6.1 on 2026-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_teacherapplicant_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherapplicant',
            name='birth_date',
            field=models.CharField(blank=True, help_text='به شمسی، مثلاً: ۱۳۷۰/۰۵/۱۲', max_length=20, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='teacherapplicant',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام پدر'),
        ),
    ]
