# Generated by Django 6.1 on 2026-09-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teacherapplicant_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.CharField(blank=True, help_text='برای محدودکردن ثبت\u200cنام دانش\u200cپژوهان به کلاس\u200cهای همان استان لازم است.', max_length=100, verbose_name='استان'),
        ),
    ]
