# Generated by Django 6.1 on 2026-09-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_branch_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.CharField(blank=True, help_text='به شمسی، مثلاً: ۱۳۷۰/۰۵/۱۲', max_length=20, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='میزان تحصیلات'),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='employee_photos/', verbose_name='عکس'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_resumes/', verbose_name='رزومه'),
        ),
    ]
