# Generated by Django 6.1 on 2026-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employee_address_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherapplicant',
            name='regtype',
            field=models.CharField(choices=[('سایت', 'ثبت از طریق سایت'), ('دستی', 'ثبت دستی توسط ادمین')], default='دستی', help_text='این فیلد نشان می\u200cدهد درخواست از طریق سایت اصلی ثبت شده یا مدیر/مسئول آموزش دستی اضافه\u200cاش کرده - ربطی به نوع همکاری (حضوری/مجازی) ندارد.', max_length=10, verbose_name='منبع ثبت'),
        ),
    ]
