# ===== مسیر این فایل در پروژه: core/migrations/0016_add_reqtype_to_employee.py (کنار manage.py) =====
# Generated by Django 6.1 on 2026-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_populate_branch_provinces'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reqtype',
            field=models.JSONField(blank=True, default=list, verbose_name='نوع تدریس'),
        ),
    ]
