# Generated by Django 6.1 on 2026-09-20 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_management', '0017_teacher_lesson_permission'),
        ('core', '0014_alter_teacherapplicant_regtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200, verbose_name='نام کلاس')),
                ('teacher_name', models.CharField(max_length=150, verbose_name='نام مدرس')),
                ('branch', models.CharField(max_length=100, verbose_name='شعبه')),
                ('term_label', models.CharField(blank=True, max_length=100, verbose_name='ترم')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ساعت کل دوره')),
                ('hourly_rate', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='نرخ هر ساعت (تومان)')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('paid_date', models.CharField(max_length=10, verbose_name='تاریخ پرداخت (شمسی)')),
                ('method', models.CharField(choices=[('bank', 'واریز بانکی'), ('card', 'کارت\u200cبه\u200cکارت'), ('cash', 'نقدی')], max_length=6, verbose_name='روش پرداخت')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='شماره پیگیری')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('canceled', 'لغوشده')], default='paid', max_length=10, verbose_name='وضعیت')),
                ('created_by_name', models.CharField(blank=True, max_length=150, verbose_name='ثبت\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('canceled_by_name', models.CharField(blank=True, max_length=150, verbose_name='لغوکننده')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='دلیل لغو')),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_payments', to='class_management.class', verbose_name='کلاس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.employee', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'پرداخت به مدرس',
                'verbose_name_plural': 'پرداخت\u200cها به مدرسین',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'ثبت پرداخت'), ('edited', 'ویرایش پرداخت'), ('canceled', 'لغو پرداخت')], max_length=10, verbose_name='عملیات')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='انجام\u200cدهنده')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('changes', models.JSONField(blank=True, default=list, verbose_name='تغییرات')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='finance.teacherpayment')),
            ],
            options={
                'verbose_name': 'سابقه\u200cی پرداخت',
                'verbose_name_plural': 'سابقه\u200cی پرداخت\u200cها',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('class_obj',), name='one_paid_payment_per_class'),
        ),
    ]
