# Generated by Django 6.1 on 2026-09-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpayment',
            name='fee_type',
            field=models.CharField(choices=[('hourly', 'ساعتی'), ('monthly', 'ماهیانه')], default='hourly', max_length=7, verbose_name='نوع حق\u200cالزحمه'),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='monthly_fee',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حق\u200cالزحمه\u200cی ماهیانه (تومان)'),
        ),
    ]
