# Generated by Django 6.1 on 2026-08-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='سال (شمسی)')),
                ('pdf', models.FileField(upload_to='calendar_pdfs/', verbose_name='فایل PDF')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='زمان آپلود')),
            ],
            options={
                'verbose_name': 'فایل PDF تقویم آموزشی',
                'verbose_name_plural': 'فایل\u200cهای PDF تقویم آموزشی',
                'ordering': ['-year'],
            },
        ),
    ]
