# Generated by Django 6.1 on 2026-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('complaint', 'انتقاد'), ('suggestion', 'پیشنهاد')], max_length=12, verbose_name='نوع')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('pending', 'بررسی نشده'), ('answered', 'پاسخ داده شد')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('replier_name', models.CharField(blank=True, max_length=100, verbose_name='نام پاسخ\u200cدهنده')),
                ('reply_text', models.TextField(blank=True, verbose_name='متن پاسخ')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'انتقاد/پیشنهاد',
                'verbose_name_plural': 'انتقادات و پیشنهادات',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
