# Generated by Django 6.1 on 2026-09-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('members', '0009_employeeotpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='members.member', verbose_name='فرستنده'),
        ),
    ]
