# Generated by Django 6.1 on 2026-09-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='نظرسنجی پایان دوره', max_length=200, verbose_name='عنوان نظرسنجی')),
                ('description', models.TextField(blank=True, default='لطفاً پیش از دریافت مدرک، به این پرسش\u200cها پاسخ دهید. نظر شما به بهبود کلاس\u200cها کمک می\u200cکند.', verbose_name='توضیحات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'نظرسنجی کلی کلاس',
                'verbose_name_plural': 'نظرسنجی کلی کلاس',
            },
        ),
        migrations.CreateModel(
            name='ClassSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن سؤال')),
                ('kind', models.CharField(choices=[('choice', 'تستی'), ('text', 'تشریحی')], default='choice', max_length=6, verbose_name='نوع')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='گزینه\u200cها')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.classsurvey')),
            ],
            options={
                'verbose_name': 'سؤال نظرسنجی',
                'verbose_name_plural': 'سؤال\u200cهای نظرسنجی',
                'ordering': ['order', 'id'],
            },
        ),
    ]
