# Generated by Django 6.1 on 2026-09-19 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0015_sitesettings_feedback_enabled'),
        ('feedback', '0003_class_survey'),
        ('members', '0009_employeeotpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=200, verbose_name='نام کلاس')),
                ('branch', models.CharField(blank=True, max_length=100, verbose_name='شعبه')),
                ('answers', models.JSONField(default=list, verbose_name='پاسخ\u200cها')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شرکت')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_response', to='class_management.enrollment', verbose_name='ثبت\u200cنام')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to='members.member', verbose_name='دانش\u200cپژوه')),
            ],
            options={
                'verbose_name': 'پاسخ نظرسنجی',
                'verbose_name_plural': 'پاسخ\u200cهای نظرسنجی',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
