# Generated by Django 6.1 on 2026-10-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0020_seminar_lesson"),
        ("feedback", "0004_class_survey_response"),
        ("members", "0009_employeeotpcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "نظرسنجی کلی",
                "verbose_name_plural": "نظرسنجی\u200cهای کلی",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="classsurveyquestion",
            name="class_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_questions",
                to="class_management.class",
                verbose_name="کلاس (فقط برای سؤال اختصاصی)",
            ),
        ),
        migrations.AlterField(
            model_name="classsurveyquestion",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="feedback.classsurvey",
            ),
        ),
        migrations.CreateModel(
            name="GeneralSurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="متن سؤال")),
                (
                    "kind",
                    models.CharField(
                        choices=[("choice", "تستی"), ("text", "تشریحی")],
                        default="choice",
                        max_length=6,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=list, verbose_name="گزینه\u200cها"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="feedback.generalsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال نظرسنجی کلی",
                "verbose_name_plural": "سؤال\u200cهای نظرسنجی کلی",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GeneralSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.CharField(blank=True, max_length=100, verbose_name="شعبه"),
                ),
                (
                    "answers",
                    models.JSONField(default=list, verbose_name="پاسخ\u200cها"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان شرکت"),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="general_survey_responses",
                        to="members.member",
                        verbose_name="دانش\u200cپژوه",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="feedback.generalsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "پاسخ نظرسنجی کلی",
                "verbose_name_plural": "پاسخ\u200cهای نظرسنجی کلی",
                "ordering": ["-submitted_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("survey", "member"), name="uniq_general_survey_member"
                    )
                ],
            },
        ),
    ]
