# Generated by Django 6.1 on 2026-09-21 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=170, unique=True, verbose_name='کلید حساب')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تلاش ناموفق')),
                ('window_started_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع بازه\u200cی شمارش')),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='مسدود تا')),
                ('last_attempt_at', models.DateTimeField(db_index=True, verbose_name='آخرین تلاش')),
                ('known', models.BooleanField(default=False, verbose_name='حساب واقعی است')),
            ],
            options={
                'verbose_name': 'شمارنده\u200cی تلاش ورود',
                'verbose_name_plural': 'شمارنده\u200cهای تلاش ورود',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('category', models.CharField(choices=[('auth', 'ورود و خروج'), ('member', 'اعضا'), ('staff', 'مدرسین و کارکنان'), ('class', 'کلاس و ثبت\u200cنام'), ('finance', 'امور مالی'), ('feedback', 'انتقادات و پیشنهادات'), ('survey', 'نظرسنجی'), ('settings', 'تنظیمات')], db_index=True, max_length=10, verbose_name='دسته')),
                ('action', models.CharField(db_index=True, max_length=40, verbose_name='کد رویداد')),
                ('summary', models.CharField(max_length=300, verbose_name='شرح')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('blocked', 'مسدود')], db_index=True, default='success', max_length=8, verbose_name='وضعیت')),
                ('actor_name', models.CharField(blank=True, max_length=150, verbose_name='انجام\u200cدهنده')),
                ('actor_role', models.CharField(blank=True, max_length=40, verbose_name='سمت')),
                ('branch', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شعبه')),
                ('target_type', models.CharField(blank=True, max_length=40, verbose_name='نوع مورد')),
                ('target_id', models.CharField(blank=True, max_length=40, verbose_name='شناسه\u200cی مورد')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='مورد')),
                ('changes', models.JSONField(blank=True, default=list, verbose_name='تغییرات')),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='شناسه\u200cی واردشده')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='مرورگر')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد لاگ',
                'verbose_name_plural': 'لاگ سامانه',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
