# Generated by Django 6.1 on 2026-09-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('auth', 'ورود و خروج'), ('member', 'اعضا'), ('teacher', 'مدرسین'), ('staff', 'کارکنان'), ('class', 'کلاس و ثبت\u200cنام'), ('finance', 'امور مالی'), ('feedback', 'انتقادات و پیشنهادات'), ('survey', 'نظرسنجی'), ('settings', 'تنظیمات')], db_index=True, max_length=10, verbose_name='دسته'),
        ),
    ]
