# Generated by Django 6.1 on 2026-08-25 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_adminaccount_alter_member_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('purpose', models.CharField(choices=[('login', 'ورود با رمز یکبار مصرف'), ('reset', 'فراموشی رمز عبور')], max_length=10, verbose_name='هدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='members.member', verbose_name='دانش\u200cپژوه')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف پیامکی',
                'verbose_name_plural': 'کدهای یکبارمصرف پیامکی',
                'ordering': ['-created_at'],
            },
        ),
    ]
