# Generated by Django 6.1 on 2026-08-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employee_multi_dept'),
        ('members', '0003_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'verbose_name': 'مدرس (تأییدشده)',
                'verbose_name_plural': 'مدرسین (تأییدشده)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.employee',),
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
            ],
            options={
                'verbose_name': 'مدرس متقاضی',
                'verbose_name_plural': 'مدرسین (متقاضی)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.teacherapplicant',),
        ),
    ]
