# Generated by Django 6.1 on 2026-08-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_teacher_teacherapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='دلیل محرومیت')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ محرومیت')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban', to='members.member')),
            ],
            options={
                'verbose_name': 'محرومیت عضو',
                'verbose_name_plural': 'محرومیت\u200cهای اعضا',
            },
        ),
    ]
