# Generated by Django 6.1 on 2026-08-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberban'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_expires_at',
            field=models.DateField(blank=True, help_text='تا این تاریخ، کارت عضویت معتبر است. فعلاً این تاریخ باید دستی (مثلاً همین\u200cجا در پنل جنگو) وارد شود؛ TODO: وقتی اتصال به دیتابیس مرکزی خانه کارگر آماده شد، این فیلد باید از آن\u200cجا همگام\u200cسازی شود.', null=True, verbose_name='تاریخ انقضای کارت عضویت'),
        ),
    ]
