# Generated by Django 6.1 on 2026-08-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_teacherapplicant_reqtype'),
        ('members', '0006_member_card_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'متصدی',
                'verbose_name_plural': 'متصدیان',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.employee',),
        ),
    ]
