# Generated by Django 6.1 on 2026-08-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.CharField(blank=True, help_text='به شمسی، مثلاً: ۱۳۷۰/۰۵/۱۲', max_length=20, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='member',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام پدر'),
        ),
    ]
