# Generated by Django 6.1 on 2026-09-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_teacherapplicant_regtype'),
        ('members', '0008_member_birth_date_member_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('purpose', models.CharField(choices=[('reset', 'فراموشی رمز عبور')], default='reset', max_length=10, verbose_name='هدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('expires_at', models.DateTimeField(verbose_name='زمان انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده\u200cشده')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='core.employee', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف پیامکی مدرس',
                'verbose_name_plural': 'کدهای یکبارمصرف پیامکی مدرسین',
                'ordering': ['-created_at'],
            },
        ),
    ]
