# Generated by Django 6.1 on 2026-08-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_calendar', '0002_calendardocument'),
        ('core', '0008_alter_teacherapplicant_reqtype'),
        ('members', '0006_member_card_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام دپارتمان')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام کلاس')),
                ('branch', models.CharField(max_length=100, verbose_name='شعبه')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('start_date', models.CharField(blank=True, max_length=20, verbose_name='تاریخ شروع')),
                ('day', models.CharField(blank=True, choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=20, verbose_name='روز هفته')),
                ('start_time', models.CharField(blank=True, max_length=10, verbose_name='ساعت شروع')),
                ('entry_time', models.CharField(blank=True, max_length=10, verbose_name='ساعت پایان/ورود')),
                ('gender', models.CharField(choices=[('مردانه', 'مردانه'), ('زنانه', 'زنانه'), ('مختلط', 'مختلط')], default='مختلط', max_length=10, verbose_name='جنسیت')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشرشده در سایت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_classes', to='class_management.class')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core.employee')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_classes', to='academic_calendar.academicterm')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='class_management.department')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100, verbose_name='شعبه')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_links', to='class_management.department')),
            ],
            options={
                'verbose_name': 'دپارتمان فعال در شعبه',
                'verbose_name_plural': 'دپارتمان\u200cهای فعال در شعب',
                'unique_together': {('branch', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='class_management.class')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='members.member')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-enrolled_at'],
                'unique_together': {('class_obj', 'member')},
            },
        ),
    ]
