# Generated by Django 6.1 on 2026-08-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی')], default='حضوری', max_length=10, verbose_name='نوع برگزاری'),
        ),
        migrations.AddField(
            model_name='class',
            name='is_national',
            field=models.BooleanField(default=False, help_text='فقط برای کلاس\u200cهای مجازی معنی دارد - یعنی دانش\u200cپژوهان همه\u200cی شعب می\u200cبینندش.', verbose_name='سراسری (بدون وابستگی به شعبه)'),
        ),
    ]
