# Generated by Django 6.1 on 2026-08-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0002_class_class_type_class_is_national'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='شعبه'),
        ),
    ]
