# Generated by Django 6.1 on 2026-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0003_alter_class_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(blank=True, max_length=50, verbose_name='روز هفته'),
        ),
    ]
