# Generated by Django 6.1 on 2026-08-29 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0004_alter_class_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('sessions', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد جلسات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='class_management.department')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='کلاس باید بر اساس یک درسِ از قبل تعریف\u200cشده ساخته شود.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='class_management.lesson', verbose_name='درس'),
        ),
    ]
