# Generated by Django 6.1 on 2026-08-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0005_lesson_class_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_registration_enabled', models.BooleanField(default=False, verbose_name='دسترسی همگان به دیدن و ثبت\u200cنام در کلاس\u200cها')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
