# Generated by Django 6.1 on 2026-08-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0006_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text=('پیش\u200cنیاز به «درس» وصل است نه به یک کلاس خاص - چون کلاس\u200cها هر ترم عوض می\u200cشوند ولی درس ثابت می\u200cماند. یعنی حتی اگر الان کلاسی برای آن درس برگزار نشود، بازهم می\u200cشود آن را به\u200cعنوان پیش\u200cنیاز انتخاب کرد.',), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_classes', to='class_management.lesson', verbose_name='درسِ پیش\u200cنیاز'),
        ),
    ]
