# Generated by Django 6.1 on 2026-08-30 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0007_alter_class_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='کپی مستقل از درسِ همان کلاس در لحظه\u200cی ثبت\u200cنام - حتی اگر بعداً کلاس حذف شود باقی می\u200cماند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='class_management.lesson'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='class_management.class'),
        ),
    ]
