# Generated by Django 6.1 on 2026-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0008_enrollment_lesson_alter_enrollment_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='has_online_exam',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، در «درج نمرات» فقط ۵۰ نمره (نمره\u200cی عملی) قابل ثبت دستی است؛ ۵۰ نمره\u200cی دیگر برای آزمون آنلاین کنار گذاشته می\u200cشود.', verbose_name='آزمون آنلاین دارد'),
        ),
    ]
