# Generated by Django 6.1 on 2026-09-04 09:36

from django.db import migrations, models


def backfill_lesson_branch(apps, schema_editor):
    """
    درس‌های موجود (که قبل از این تغییر ساخته شده‌اند) شعبه ندارند؛ اگر
    کلاسی از همان درس در دیتابیس وجود داشته باشد، همان شعبه‌ی آن کلاس را
    برای درس هم می‌گذاریم - در غیر این صورت، شعبه‌ی مرکزی به‌عنوان یک
    مقدار پیش‌فرض معقول انتخاب می‌شود (بعداً از پنل قابل اصلاح است).
    """
    Lesson = apps.get_model('class_management', 'Lesson')
    Class = apps.get_model('class_management', 'Class')
    for lesson in Lesson.objects.filter(branch=''):
        matching_class = Class.objects.filter(lesson=lesson).exclude(branch='').first()
        lesson.branch = matching_class.branch if matching_class else 'دفتر مرکزی خانه کارگر'
        lesson.save(update_fields=['branch'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0009_class_has_online_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['branch', 'department__name', 'name'], 'verbose_name': 'درس', 'verbose_name_plural': 'درس\u200cها'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='branch',
            field=models.CharField(default='', max_length=100, verbose_name='شعبه'),
        ),
        migrations.RunPython(backfill_lesson_branch, noop_reverse),
    ]
