# Generated by Django 6.1 on 2026-09-05 11:35

from django.db import migrations, models


def preserve_old_value(apps, schema_editor):
    """
    قبل از این تغییر، اگر ادمین دستی سایت را باز/بسته کرده بود (مقدار
    قدیمیِ بولی)، همان تصمیم را به‌عنوان حالت دستیِ معادل نگه می‌داریم -
    نه این‌که همه‌چیز ناگهان روی «خودکار» بیفتد و رفتار غیرمنتظره‌ای پیش بیاید.
    """
    SiteSettings = apps.get_model('class_management', 'SiteSettings')
    for obj in SiteSettings.objects.all():
        obj.registration_mode = 'open' if obj.public_registration_enabled else 'closed'
        obj.save(update_fields=['registration_mode'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0010_alter_lesson_options_lesson_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='registration_mode',
            field=models.CharField(choices=[('auto', 'خودکار (بر اساس تقویم آموزشی)'), ('open', 'باز - همیشه (دستی)'), ('closed', 'بسته - همیشه (دستی)')], default='auto', max_length=10, verbose_name='وضعیت دسترسی همگان به ثبت\u200cنام'),
        ),
        migrations.RunPython(preserve_old_value, noop_reverse),
        migrations.RemoveField(
            model_name='sitesettings',
            name='public_registration_enabled',
        ),
    ]
