# Generated by Django 6.1 on 2026-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0011_remove_sitesettings_public_registration_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='اگر کلاس «آزمون آنلاین» فعال داشته باشد، حداکثر ۵۰ (نمره\u200cی عملی)؛ وگرنه حداکثر ۱۰۰.', null=True, verbose_name='نمره'),
        ),
    ]
