# Generated by Django 6.1 on 2026-09-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0012_enrollment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='absent',
            field=models.BooleanField(default=False, help_text='اگر فرد اصلاً در کلاس حضور نداشته، این True می\u200cشود و نمره خودکار صفر می\u200cشود - حتی اگر کلاس آزمون آنلاین هم داشته باشد، دیگر اجازه\u200cی شرکت در آن را ندارد (چون در خودِ کلاس شرکت نکرده است). این حالت باعث می\u200cشود در «سوابق آموزشی» به\u200cجای «مردود - عدم کسب نمره کافی»، دقیقاً «مردود - عدم حضور در کلاس» نشان داده شود.', verbose_name='غایب در کلاس'),
        ),
    ]
