# Generated by Django 6.1 on 2026-09-09 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0013_enrollment_absent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن سؤال')),
                ('options', models.JSONField(default=list, help_text='لیستی ۲ تا ۴ عضوی از {"text": "...", "is_correct": true/false}', verbose_name='گزینه\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='class_management.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'بانک سوالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
