# Generated by Django 6.1 on 2026-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0014_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='feedback_enabled',
            field=models.BooleanField(default=True, verbose_name='بخش انتقادات و پیشنهادات در سایت فعال است'),
        ),
    ]
