# Generated by Django 6.1 on 2026-09-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0015_sitesettings_feedback_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='age_limit_enabled',
            field=models.BooleanField(default=False, verbose_name='رده سنی دارد'),
        ),
        migrations.AddField(
            model_name='class',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداکثر سن'),
        ),
        migrations.AddField(
            model_name='class',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداقل سن'),
        ),
    ]
