# Generated by Django 6.1 on 2026-09-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0016_class_age_limit'),
        ('core', '0014_alter_teacherapplicant_regtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLessonPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور مجوز')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_permissions', to='class_management.lesson', verbose_name='درس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_permissions', to='core.employee', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'مجوز تدریس',
                'verbose_name_plural': 'مجوزهای تدریس',
                'ordering': ['teacher_id', 'lesson_id'],
                'unique_together': {('teacher', 'lesson')},
            },
        ),
    ]
