# ===== مسیر این فایل در پروژه: class_management/migrations/0018_add_class_type_to_department_and_lesson.py (کنار manage.py) =====
# Generated by Django 6.1 on 2026-10-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0017_teacher_lesson_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='class_type',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی')], default='حضوری', max_length=10, verbose_name='نوع برگزاری'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='class_type',
            field=models.CharField(choices=[('حضوری', 'حضوری'), ('مجازی', 'مجازی')], default='حضوری', max_length=10, verbose_name='نوع برگزاری'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دپارتمان'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('name', 'class_type'), name='unique_department_name_per_type'),
        ),
    ]
