# Generated by Django 6.1 on 2026-10-08 16:56

import class_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0020_seminar_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="عنوان"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=class_management.models.slide_image_path,
                        verbose_name="تصویر (دسکتاپ)",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=class_management.models.slide_image_path,
                        verbose_name="تصویر موبایل (اختیاری)",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="متن جایگزین تصویر",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="لینک"
                    ),
                ),
                (
                    "open_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="باز شدن در تب جدید"
                    ),
                ),
                (
                    "text_position",
                    models.CharField(
                        choices=[("right", "راست"), ("center", "وسط"), ("left", "چپ")],
                        default="right",
                        max_length=10,
                        verbose_name="جایگاه متن",
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        choices=[("light", "روشن (سفید)"), ("dark", "تیره")],
                        default="light",
                        max_length=10,
                        verbose_name="رنگ متن",
                    ),
                ),
                (
                    "overlay",
                    models.PositiveSmallIntegerField(
                        default=35, verbose_name="تیرگی روی تصویر (۰ تا ۸۰ درصد)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع نمایش"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان نمایش"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "اسلاید",
                "verbose_name_plural": "اسلایدها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slide_autoplay",
            field=models.BooleanField(
                default=True, verbose_name="پخش خودکار اسلاید شو"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slide_effect",
            field=models.CharField(
                choices=[("slide", "لغزش"), ("fade", "محو شدن")],
                default="slide",
                max_length=10,
                verbose_name="افکت انتقال",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slide_interval",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="مدت نمایش هر اسلاید (ثانیه)"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slide_show_arrows",
            field=models.BooleanField(default=True, verbose_name="نمایش فلش\u200cها"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="slide_show_dots",
            field=models.BooleanField(
                default=True, verbose_name="نمایش نقطه\u200cهای پایین"
            ),
        ),
    ]
