# Generated by Django 6.1 on 2026-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0021_slideshow"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="rules_text",
            field=models.TextField(
                blank=True, default="", verbose_name="قوانین و مقررات"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="rules_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین ویرایش قوانین"
            ),
        ),
    ]
