# Generated by Django 6.1 on 2026-10-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_management", "0022_rules_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        max_length=3000,
                        verbose_name="متن اطلاعیه",
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="خالی = همه\u200cی شعب",
                        max_length=150,
                        verbose_name="شعبه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "اطلاعیه",
                "verbose_name_plural": "اطلاعیه\u200cها",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
